13-DeploymentFinaldep/flaskblog/posts/forms.py
# flaskblog/posts/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    image = FileField('Post Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])  # Add image field
    submit = SubmitField('Post')
class CommentForm(FlaskForm):
    content = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

13-DeploymentFinaldep/flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user  # Import current_user from flask_login
from flaskblog.models import Post
from flaskblog.posts.forms import CommentForm

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        # Display blog posts if user is logged in
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        form = CommentForm()  # Assuming you want to add comments functionality when logged in
        return render_template('home.html', posts=posts, form=form)
    else:
        # Display landing page if user is not logged in
        return render_template('welcome.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

13-DeploymentFinaldep/flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, current_app, jsonify
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment, PostLike
from flaskblog.posts.forms import PostForm, CommentForm
import os
import secrets
from PIL import Image

posts = Blueprint('posts', __name__)

def save_post_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/post_pics', picture_fn)

    output_size = (500, 500)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        image_file = save_post_picture(form.image.data) if form.image.data else None
        post = Post(title=form.title.data, content=form.content.data, picture=image_file, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post_id).all()
    form = CommentForm()
    return render_template('post.html', title=post.title, post=post, form=form, comments=comments)

@posts.route("/post/<int:post_id>/comment", methods=['POST'])
@login_required
def comment_post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, user_id=current_user.id, post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been added!', 'success')
    return redirect(url_for('posts.post', post_id=post_id))

@posts.route("/post/<int:post_id>/like", methods=['POST'])
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    post_like = PostLike.query.filter_by(user_id=current_user.id, post_id=post_id).first()

    if post_like:
        if post_like.liked:
            db.session.delete(post_like)
        else:
            post_like.liked = True
    else:
        post_like = PostLike(user_id=current_user.id, post_id=post_id, liked=True)
        db.session.add(post_like)

    db.session.commit()

    likes_count = PostLike.query.filter_by(post_id=post_id, liked=True).count()
    dislikes_count = PostLike.query.filter_by(post_id=post_id, liked=False).count()

    return jsonify({'likes': likes_count, 'dislikes': dislikes_count})

@posts.route("/post/<int:post_id>/dislike", methods=['POST'])
@login_required
def dislike_post(post_id):
    post = Post.query.get_or_404(post_id)
    post_like = PostLike.query.filter_by(user_id=current_user.id, post_id=post_id).first()

    if post_like:
        if not post_like.liked:
            db.session.delete(post_like)
        else:
            post_like.liked = False
    else:
        post_like = PostLike(user_id=current_user.id, post_id=post_id, liked=False)
        db.session.add(post_like)

    db.session.commit()

    likes_count = PostLike.query.filter_by(post_id=post_id, liked=True).count()
    dislikes_count = PostLike.query.filter_by(post_id=post_id, liked=False).count()

    return jsonify({'likes': likes_count, 'dislikes': dislikes_count})

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_post_picture(form.image.data)
            post.picture = image_file
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route('/post/<int:post_id>/full_content', methods=['GET'])
def get_full_content(post_id):
    post = Post.query.get_or_404(post_id)
    return post.content

13-DeploymentFinaldep/flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_confirmation_email, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        # Send confirmation email after registration
        send_confirmation_email(user)
        flash('An email has been sent with instructions to confirm your account.', 'info')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # Allow login without email confirmation
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/confirm/<token>")
def confirm_token(token):
    user = User.verify_confirm_token(token)
    if user is None:
        flash('The confirmation link is invalid or has expired.', 'warning')
        return redirect(url_for('main.home'))

    user.confirmed = True
    db.session.commit()
    flash('Your account has been confirmed! You can now log in.', 'success')
    return redirect(url_for('users.login'))

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash('An email has been sent with instructions to reset your password.', 'info')
        else:
            flash('No account found with that email.', 'warning')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

13-DeploymentFinaldep/flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
  

	    <div>	    
	<p>
"This web application is designed to promote and strengthen the culture of safety among all individuals working in the industry. It targets professionals at all levels, from operators and technicians to managers, providing proven methods and practical scenarios to raise awareness of safety issues. By encouraging active participation from everyone, the application fosters a collaborative environment where safety becomes everyone's responsibility. With interactive tools and educational resources, it helps build collective awareness and ensures the rigorous application of best safety practices in the workplace."
</p>

    </div>

    <div><p>
</p> </div>
{% endblock content %}

13-DeploymentFinaldep/flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>

                <!-- Truncate the post content and add a "Read More" button -->
                <p class="article-content" id="content-{{ post.id }}">
                    {% if post.content|length > 100 %}
                        {{ post.content[:100] }}...
                        <a href="#" class="read-more" data-post-id="{{ post.id }}">Read More</a>
                    {% else %}
                        {{ post.content }}
                    {% endif %}
                </p>

                <!-- Display the post picture if it exists -->
                {% if post.picture %}
                    <img class="img-fluid mt-3" src="{{ url_for('static', filename='post_pics/' + post.picture) }}" alt="Post Picture">
                {% endif %}

                <!-- Like/Dislike Section -->
                <div class="like-dislike-section mt-3">
                    <button class="btn btn-outline-success btn-sm like-btn" data-post-id="{{ post.id }}">
                        Like <span class="like-count">{{ post.like_count }}</span>
                    </button>
                    <button class="btn btn-outline-danger btn-sm dislike-btn" data-post-id="{{ post.id }}">
                        Dislike <span class="dislike-count">{{ post.dislike_count }}</span>
                    </button>
                </div>

                <!-- Comments Section -->
                <div class="comments-section mt-4">
                    <h5>Comments:</h5>
                    {% if post.comments %}
                        <div class="comment-list">
                            {% for comment in post.comments %}
                                <div class="comment-item">
                                    <strong>{{ comment.user.username }}</strong>:
                                    <p>{{ comment.content }}</p>
                                    <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No comments yet. Be the first to comment!</p>
                    {% endif %}

                    {% if current_user.is_authenticated %}
                        <!-- Add a Comment Form -->
                        <form method="POST" action="{{ url_for('posts.comment_post', post_id=post.id) }}" class="mt-2">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.content.label(class="form-control-label") }}
                                {{ form.content(class="form-control", rows=2) }}
                            </div>
                            <button type="submit" class="btn btn-primary">Add Comment</button>
                        </form>
                    {% else %}
                        <p>You must be logged in to comment.</p>
                    {% endif %}
                </div>
            </div>
        </article>
    {% endfor %}

    <!-- Pagination Links -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

<script>
    // JavaScript for dynamic "Read More"
    document.querySelectorAll('.read-more').forEach(button => {
        button.addEventListener('click', event => {
            event.preventDefault();
            const postId = button.getAttribute('data-post-id');
            fetch(`/post/${postId}/full_content`)
                .then(response => response.text())
                .then(fullContent => {
                    document.getElementById(`content-${postId}`).innerHTML = fullContent;
                });
        });
    });

    // JavaScript for Like/Dislike buttons
    document.querySelectorAll('.like-btn').forEach(button => {
        button.addEventListener('click', () => {
            const postId = button.getAttribute('data-post-id');
            fetch(`/post/${postId}/like`, { method: 'POST' })
                .then(response => response.json())
                .then(data => {
                    button.querySelector('.like-count').innerText = data.likes;
                    button.nextElementSibling.querySelector('.dislike-count').innerText = data.dislikes;
                });
        });
    });

    document.querySelectorAll('.dislike-btn').forEach(button => {
        button.addEventListener('click', () => {
            const postId = button.getAttribute('data-post-id');
            fetch(`/post/${postId}/dislike`, { method: 'POST' })
                .then(response => response.json())
                .then(data => {
                    button.querySelector('.dislike-count').innerText = data.dislikes;
                    button.previousElementSibling.querySelector('.like-count').innerText = data.likes;
                });
        });
    });
</script>

{% endblock content %}

13-DeploymentFinaldep/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>SaftyBlog - {{ title }}</title>
    {% else %}
        <title>SaftyBlog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">SafetyBlog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if current_user.role == 1 %}
                  <!-- Admin Button -->
                  <a class="nav-item nav-link btn btn-outline-light btn-sm" href="/admin">Admin Panel</a>
		  <a class="nav-item nav-link" href="{{ url_for('analytics.analytics_home') }}">Analytics</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
		

              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Make It Safe</h3>
            <p class='text-muted'>"Safety isn’t just a priority—it’s a way of life."
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</body>
</html>

13-DeploymentFinaldep/flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>

        <!-- Display post image if available -->
        {% if post.picture %}
        <img src="{{ url_for('static', filename='post_pics/' + post.picture) }}" class="img-fluid mt-3" alt="Post Image">
        {% endif %}

        <!-- Like/Dislike Section -->
        <div class="mt-4">
            <a href="{{ url_for('posts.like_post', post_id=post.id) }}" class="btn btn-outline-success {% if current_user.has_liked_post(post) %}disabled{% endif %}">Like</a>
            <span class="badge badge-success">{{ post.like_count }}</span>

            <a href="{{ url_for('posts.dislike_post', post_id=post.id) }}" class="btn btn-outline-danger {% if current_user.has_disliked_post(post) %}disabled{% endif %}">Dislike</a>
            <span class="badge badge-danger">{{ post.dislike_count }}</span>
        </div>

        <!-- Comments Section -->
        <div class="comments-section mt-4">
            <h5>Comments:</h5>
            {% for comment in post.comments %}
            <div class="comment mb-3">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + comment.user.image_file) }}">
                <strong>{{ comment.user.username }}</strong> said:
                <p>{{ comment.content }}</p>
                <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
            </div>
            {% endfor %}

            {% if current_user.is_authenticated %}
            <!-- Add a Comment Form -->
            <form method="POST" action="{{ url_for('posts.comment_post', post_id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {{ form.content(class="form-control", rows=2) }}
                </div>
                <button type="submit" class="btn btn-primary mt-2">Add Comment</button>
            </form>
            {% else %}
            <p>You must be logged in to comment.</p>
            {% endif %}
        </div>
    </div>
</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

13-DeploymentFinaldep/flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="{{ post.author.username }}'s profile picture">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>

                {% if post.picture %}
                    <!-- Display the post picture if it exists -->
                    <img class="img-fluid mt-3" src="{{ url_for('static', filename='post_pics/' + post.picture) }}" alt="Post Picture">
                {% endif %}

                <!-- Like/Dislike Section -->
                <div class="post-actions mt-2">
                    <a href="{{ url_for('posts.like_post', post_id=post.id) }}" class="btn btn-success btn-sm">Like ({{ post.likes }})</a>
                    <a href="{{ url_for('posts.dislike_post', post_id=post.id) }}" class="btn btn-danger btn-sm">Dislike ({{ post.dislikes }})</a>
                </div>

                <!-- Display number of comments and link to the post -->
                <p><a href="{{ url_for('posts.post', post_id=post.id) }}">View all comments ({{ post.comments|length }})</a></p>
            </div>
        </article>
    {% endfor %}

    <!-- Pagination links -->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    <li class="page-item {% if posts.page == page_num %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock content %}